title: "LEAP Data Library Prototype"
description: >
  A prototype test for the LEAP Data Library refactor
recipes:
  - id: "proto_a"
    object: "recipe:proto_a"
    description: Some description for proto_a
    data_store: "this"
    pyramid_store: "gs://some-bucket/some-path/some-store.zarr"
    axes:
      - 'T': 'time'
      - 'Y': 'latitude'
  - id: "proto_b"
    object: "recipe:proto_b"
    description: Some description for proto_b
    data_store: "this"
    pyramid_store: "gs://some-bucket/some-other-path/some-other-store.zarr"
    axes:
      - 'T': 'time'
      - 'Y': 'latitude'
provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/record/7761881#.ZFv9OS-B30p
    - name: "Nathaniel et al."
      description: "Authors of MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations"
      roles:
        - producer
        - licensor
  license: "CC-BY-4.0"