title: "LEAP Data Library Prototype"
description: >
  A prototype test for the LEAP Data Library refactor
recipes:
  - id: "proto_a"
    object: "recipe:proto_a"

  - id: "proto_b"
    object: "recipe:proto_b"

provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/record/7761881#.ZFv9OS-B30p
    - name: "Nathaniel et al."
      description: "Authors of MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations"
      roles:
        - producer
        - licensor
  license: "CC-BY-4.0"