name: Deploy Recipes to Google Dataflow

env:
  JOB_NAME: ${{ github.event.inputs.recipe_id }}-${{ github.run_id }}-${{ github.run_attempt }}


on:
  workflow_dispatch:
    inputs:
      recipe_id:
        description: 'The id of a single recipe to submit to Dataflow'
        required: true
        default: 'all'

jobs:
  deploy-recipes:
    name: deploy-recipes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pangeo-forge-runner
      - name: "Deploy recipes"
        run: |
          pangeo-forge-runner bake \
            --repo=${{ github.server_url }}/${{ github.repository }}.git \
            --ref=${{ github.sha }} \
            --feedstock-subdir='feedstock' \
            --Bake.job_name=$JOB_NAME \
            --Bake.recipe_id=${{ github.event.inputs.recipe_id }} \
            -f configs/config_dataflow.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      - name: Wait for job completion
        uses: ./.github/workflows/check_dataflow_jobs.yaml
        with:
          jobname: $JOB_NAME
      - name: Just something else
        run: echo "This is just another step"
      