name: Update Attributes from meta.yaml

on:
  workflow_dispatch:

jobs:
  deploy-recipes:
    name: deploy-recipes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install zarr gcsfs ruamel.yaml
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: "Run Attribute update script"
        run: |
          python scripts/update_attrs.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"