name: Catalog

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: validate feedstock entry and generate catalog
        uses: leap-stc/data-catalog-actions/leap-catalog@main
        with:
          generation-single: "./feedstock/catalog.yaml"
          output-directory: "./"

      - name: display catalog
        run: |
          cat output/consolidated-web-catalog.json | jq
